[project]
name = "niripy"
version = "0.2.7"
authors = [
  { name = "Kevin McNamara", email = "kevin.j.mcnamara+tech@proton.me" },
]
description = "Python bindings for Niri."
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.12"
dependencies = ["pydantic>=2.12.4"]
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Operating System :: POSIX :: Linux",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Desktop Environment :: Window Managers",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Typing :: Typed",
]

[project.urls]
Homepage = "https://github.com/kjmcnamara1/niripy"
Issues = "https://github.com/kjmcnamara1/niripy/issues"

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[dependency-groups]
dev = [
  "icecream>=2.1.9",
  "pytest-cov>=7.0.0",
  "ruff>=0.15.6",
  "ty>=0.0.23",
  "vermin>=1.8.0",
]
docs = [
  "griffe-pydantic>=1.3.1",
  "markdown-pycon>=1.0.1",
  "mike>=2.1.3",
  "mkdocs-git-committers-plugin-2>=2.5.0",
  "mkdocs-git-revision-date-localized-plugin>=1.5.1",
  "mkdocs-material>=9.7.2",
  "mkdocstrings[python]>=1.0.3",
  "termynal>=0.13.1",
]

[tool.ruff]
exclude = ["tests"]

[tool.pyright]
ignore = ["tests"]
reportAny = "none"
reportExplicitAny = "none"

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true
